---
- name: Check Disk Usage and Compare with fstab
  hosts: all  # Adjust to your target hosts
  become: true  # Run with sudo privileges
  gather_facts: false

  tasks:
    - name: Run df -Th and capture output
      ansible.builtin.shell: df -Th
      register: df_output
      changed_when: false

    - name: Print df -Th output
      ansible.builtin.debug:
        msg: "{{ df_output.stdout_lines }}"

    - name: Parse mounted filesystems from df -Th
      ansible.builtin.set_fact:
        mounted_filesystems: "{{ df_output.stdout_lines | select('match', '^/dev/|^UUID=|^LABEL=') | map('regex_replace', '\\s+', ' ') | map('split', ' ') | map(attribute=6) | list }}"

    - name: Read /etc/fstab content
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Parse fstab entries (mount points)
      ansible.builtin.set_fact:
        fstab_mounts: "{{ (fstab_content['content'] | b64decode).split('\n') | reject('match', '^#') | reject('equalto', '') | map('regex_replace', '\\s+', ' ') | map('split', ' ') | map(attribute=1) | list }}"

    - name: Print mounted filesystems from df
      ansible.builtin.debug:
        msg: "Mounted filesystems: {{ mounted_filesystems }}"

    - name: Print fstab mount points
      ansible.builtin.debug:
        msg: "fstab mount points: {{ fstab_mounts }}"

    - name: Find mounts in df not in fstab (possible dynamic or tmpfs mounts)
      ansible.builtin.set_fact:
        df_not_in_fstab: "{{ mounted_filesystems | difference(fstab_mounts) }}"

    - name: Find entries in fstab not mounted (possible unmounted filesystems)
      ansible.builtin.set_fact:
        fstab_not_mounted: "{{ fstab_mounts | difference(mounted_filesystems) }}"

    - name: Print mismatches
      ansible.builtin.debug:
        msg:
          - "Mounts in df but not in fstab: {{ df_not_in_fstab }}"
          - "Entries in fstab but not mounted: {{ fstab_not_mounted }}"
      when: df_not_in_fstab | length > 0 or fstab_not_mounted | length > 0
      failed_when: false  # Don't fail the play, just report

    - name: Print no mismatches if none found
      ansible.builtin.debug:
        msg: "No mismatches found between df mounts and fstab entries."
      when: df_not_in_fstab | length == 0 and fstab_not_mounted | length == 0