---
- name: Verify /etc/fstab entries against df -Th
  hosts: all  # Adjust to your target hosts
  become: true  # Run with sudo privileges
  gather_facts: false

  tasks:
    - name: Run df -Th and capture output
      ansible.builtin.shell: df -Th
      register: df_output
      changed_when: false

    - name: Print df -Th output
      ansible.builtin.debug:
        msg: "{{ df_output.stdout_lines }}"

    - name: Parse mounted filesystems from df -Th
      ansible.builtin.set_fact:
        mounted_filesystems: "{{ df_output.stdout_lines | select('match', '^/dev/|^UUID=|^LABEL=') | map('regex_replace', '\\s+', ' ') | map('split', ' ') | map(attribute=6) | list }}"

    - name: Read /etc/fstab content
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Parse fstab entries (mount points)
      ansible.builtin.set_fact:
        fstab_mounts: "{{ (fstab_content['content'] | b64decode).split('\n') | reject('match', '^#') | reject('equalto', '') | map('regex_replace', '\\s+', ' ') | map('split', ' ') | map(attribute=1) | select('match', '^/') | list }}"

    - name: Print mounted filesystems from df
      ansible.builtin.debug:
        msg: "Mounted filesystems (from df -Th): {{ mounted_filesystems }}"

    - name: Print fstab mount points
      ansible.builtin.debug:
        msg: "fstab mount points: {{ fstab_mounts }}"

    - name: Check for fstab entries not mounted
      ansible.builtin.set_fact:
        fstab_not_mounted: "{{ fstab_mounts | difference(mounted_filesystems) }}"

    - name: Report mounts status
      ansible.builtin.debug:
        msg: >-
          {% if fstab_not_mounted | length == 0 %}
          All mounts are good: All /etc/fstab entries ({{ fstab_mounts | join(', ') }}) are mounted.
          {% else %}
          Mounts are not good: The following /etc/fstab entries are not mounted: {{ fstab_not_mounted | join(', ') }}
          {% endif %}