---
- name: Disk Usage and Mount Verification Playbook
  hosts: all  # Adjust to your inventory group for all VMs
  become: yes  # Run with sudo privileges
  gather_facts: no  # No need for facts gathering

  tasks:
    - name: Get df -Th output
      command: df -Th
      register: df_output
      changed_when: false

    - name: Display df -Th output
      debug:
        msg: "{{ df_output.stdout_lines }}"

    - name: Verify mounts and parse fstab
      block:
        - name: Get /etc/fstab contents
          command: cat /etc/fstab
          register: fstab_content
          changed_when: false

        - name: Compare mount points
          set_fact:
            fstab_mounts: "{{ fstab_content.stdout_lines | select('match', '^[^#].+') | reject('match', 'swap') | map('split') | select('length', '>=', 4) | map(attribute=1) | list }}"
            mounted_filesystems: "{{ df_output.stdout_lines[1:] | map('regex_replace', '\\s+', ' ') | map('split', ' ') | map(attribute=6) | list }}"
            missing_mounts: "{{ fstab_mounts | difference(mounted_filesystems) }}"
      no_log: true  # Suppress intermediate output

    - name: Report mount verification
      debug:
        msg: "{{ 'All mounts are good on ' + inventory_hostname if missing_mounts | length == 0 else 'Missing mounts on ' + inventory_hostname + ': ' + missing_mounts | join(', ') }}"

    - name: Check and report exceeding disk usage
      debug:
        msg: "{{ 'Filesystem ' + item.split()[0] + ' or mount point ' + item.split()[6] + ' on this host exceeds 45% with ' + item.split()[4] + '.' }}"
      loop: "{{ df_output.stdout_lines[1:] }}"
      when: item.split()[4] | default('0%') | regex_replace('%', '') | int > 45
      no_log: "{{ item.split()[4] | default('0%') | regex_replace('%', '') | int <= 45 }}"  # Suppress non-exceeding items