---
- name: Disk Usage and Mount Verification Playbook
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get df -Th output
      command: df -Th
      register: df_output
      changed_when: false
      no_log: true   # 🔇 hide this task from all hosts

    - name: Report exceeding disk usage
      debug:
        msg: >-
          {% for line in df_output.stdout_lines[1:] %}
          {% set usage = (line.split()[5] | default('0%') | regex_replace('%','') | int) %}
          {% if usage > 45 %}
          Filesystem {{ line.split()[0] }} or mount point {{ line.split()[6] }}
          on this host exceeds 45% with {{ line.split()[5] }}.
          {% endif %}
          {% endfor %}
      when: >
        df_output.stdout_lines[1:] | map('regex_search','([0-9]+)%') |
        map('first') | map('int') | select('>',45) | list | length > 0
