---
- name: Disk Usage and Mount Verification Playbook
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get df -Th output
      command: df -Th
      register: df_output
      changed_when: false

    - name: Display df -Th output
      debug:
        msg: "{{ df_output.stdout_lines }}"

    - name: Verify mounts
      shell: |
        fstab_mounts=$(awk '!/^#/ && $3 != "swap" && NF >= 4 {print $2}' /etc/fstab | sort -u)
        df_mounts=$(df -Th | awk 'NR>1 {print $NF}' | sort -u)
        missing=$(comm -23 <(echo "$fstab_mounts") <(echo "$df_mounts") | tr '\n' ',' | sed 's/,$//')
        if [ -n "$missing" ]; then
          echo "Missing mounts on {{ inventory_hostname }}: $missing"
        fi
      register: mount_check
      changed_when: false

    - name: Report mount verification
      debug:
        msg: "{{ mount_check.stdout }}"
      when: mount_check.stdout != ""

    - name: Report exceeding disk usage
      debug:
        msg: >-
          {% set risky = [] %}
          {% for line in df_output.stdout_lines[1:] %}
            {% set cols = line.split() %}
            {% set usage = (cols[5] | regex_replace('%','') | int) %}
            {% if usage > 45 %}
              {% set _ = risky.append(
                "Filesystem %s or mount point %s on this host exceeds 45%% with %s."
                % (cols[0], cols[6], cols[5])
              ) %}
            {% endif %}
          {% endfor %}
          {{ risky | join('\n') }}
      when: >-
        df_output.stdout_lines[1:] |
        map('split') |
        selectattr('5','defined') |
        map('5') |
        map('regex_replace','%','') |
        map('int') |
        select('>',45) | list | length > 0
