---
- name: Deploy updated Nagios configs from GitHub
  hosts: "{{ nagios_server }}"
  become: true
  vars:
    nagios_config_repo: "git@github.com:BhargavM9/Nagios-OLAM.git"
    nagios_config_dir: "/home/nagios/nagios-config-tmp"
    nagios_target_dir: "/usr/local/nagios/etc"
    nagios_cfg_path: "/usr/local/nagios/etc/nagios.cfg"

  tasks:

    - name: Ensure required packages are installed (git and rsync)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - rsync

    - name: Clone or update Nagios Git repo as nagios
      git:
        repo: "{{ nagios_config_repo }}"
        dest: "{{ nagios_config_dir }}"
        version: main
        update: yes
        accept_hostkey: yes
        force: yes
      become_user: nagios

    - name: Rsync only updated files to Nagios config directory
      command: >
        rsync -az
        --exclude='.git'
        --exclude='htpasswd.users'
        {{ nagios_config_dir }}/ {{ nagios_target_dir }}/
      args:
        warn: false

    - name: Validate Nagios configuration
      command: "/usr/local/nagios/bin/nagios -v {{ nagios_cfg_path }}"
      register: nagios_check
      changed_when: false
      failed_when: "'Error:' in nagios_check.stdout or nagios_check.rc != 0"

    - name: Restart Nagios service if validation passed
      service:
        name: nagios
        state: restarted
