---
- name: Deploy Nagios configs from OLAM GitHub repo
  hosts: "{{ nagios_server }}"
  become: true
  vars:
    nagios_config_repo: "git@github.com:BhargavM9/Nagios-OLAM.git"
    nagios_config_dir: "/home/nagios/nagios-config-tmp"
    nagios_target_dir: "/usr/local/nagios/etc"

  tasks:
  
    - name: Clone or update Git repo as lxadmin
      git:
        repo: "{{ nagios_config_repo }}"
        dest: "{{ nagios_config_dir }}"
        version: main
        update: yes
        accept_hostkey: yes
      become_user: nagios

    - name: Find all files to copy (excluding htpasswd.users)
      find:
        paths: "{{ nagios_config_dir }}"
        recurse: yes
        patterns: '*'
        excludes: 'htpasswd.users'
      register: nagios_files

    - name: Copy Nagios config files (excluding htpasswd.users)
      copy:
        src: "{{ item.path }}"
        dest: "{{ nagios_target_dir }}/{{ item.path | regex_replace(nagios_config_dir + '/', '') }}"
        owner: nagios
        group: nagios
        mode: '0644'
      loop: "{{ nagios_files.files }}"

    - name: Restart Nagios service
      service:
        name: nagios
        state: restarted
