---
- name: Full Prepatch Validation for OLAM
  hosts: all
  become: true
  gather_facts: true

  vars:
    var_mount_point: "/var"

  tasks:

    - name: Check uptime and print
      command: uptime
      register: uptime_output
      changed_when: false
    - debug:
        msg: "{{ uptime_output.stdout }}"

    - name: Check last reboot time and print
      command: who -b
      register: last_reboot
      changed_when: false
    - debug:
        msg: "{{ last_reboot.stdout }}"

    - name: Show currently logged-in users and print
      command: who
      register: logged_users
      changed_when: false
    - debug:
        msg: "{{ logged_users.stdout_lines }}"

    - name: Check disk usage on / and print
      command: df -Th /
      register: root_disk
      changed_when: false
    - debug:
        var: root_disk.stdout_lines

    - name: Check disk usage on /boot and print
      command: df -h /boot
      register: boot_space
      changed_when: false
    - debug:
        var: boot_space.stdout_lines

    - name: Check memory usage and print
      command: free -h
      register: mem_usage
      changed_when: false
    - debug:
        var: mem_usage.stdout_lines

    - name: Check load average and print
      command: cat /proc/loadavg
      register: load_avg
      changed_when: false
    - debug:
        msg: "{{ load_avg.stdout }}"

    - name: List running services and print
      command: systemctl list-units --type=service --state=running
      register: running_services
      changed_when: false
    - debug:
        var: running_services.stdout_lines

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      when: reboot_required.stat.exists
      debug:
        msg: "Reboot is required before patching!"

    - name: Check if yum/dnf is locked
      stat:
        path: /var/run/yum.pid
      register: yum_lock

    - name: Warn if yum is currently running
      when: yum_lock.stat.exists
      debug:
        msg: "YUM/DNF is currently running! Investigate before patching."

    # ==========================
    #  Patch Size Estimation
    # ==========================

    - name: Simulate dnf update
      command: dnf update --assumeno
      register: dnf_output
      changed_when: false
      failed_when: false

    - name: Split dnf output into lines
      set_fact:
        dnf_stdout_lines: "{{ dnf_output.stdout.split('\n') }}"

    - name: Print dnf dry-run output
      debug:
        var: dnf_stdout_lines

    - name: Find patch size line
      set_fact:
        dnf_patch_size_line: >-
          {{ dnf_stdout_lines | select('search', 'Total download size:') | list | first | default('') }}

    - name: Parse patch size to MB
      set_fact:
        dnf_required_space_mb: >-
          {% set size = dnf_patch_size_line | regex_search('([0-9.]+)') | float %}
          {% set unit = dnf_patch_size_line | regex_search('[0-9.]+ ([A-Z])') %}
          {% if unit == 'G' %}
            {{ (size * 1024) | round }}
          {% elif unit == 'K' %}
            {{ (size / 1024) | round }}
          {% else %}
            {{ size | round }}
          {% endif %}
      when: dnf_patch_size_line != ''

    - name: Show patch size result
      debug:
        msg: >-
          {% if dnf_patch_size_line != '' %}
             Patch size estimate: {{ dnf_required_space_mb }} MB
          {% else %}
             System is already up to date. No patching required.
          {% endif %}

    - name: Get available space in /var (in MB)
      command: df -m {{ var_mount_point }}
      register: var_space
      changed_when: false

    - name: Extract /var available space
      set_fact:
        var_available_space_mb: "{{ var_space.stdout_lines[1].split()[3] | int }}"

    - name: Print available space in /var
      debug:
        msg: "Available space in /var: {{ var_available_space_mb }} MB"

    - name: Fail if /var space is insufficient for patch
      fail:
        msg: "Not enough space in /var. Required: {{ dnf_required_space_mb }} MB, Available: {{ var_available_space_mb }} MB"
      when:
        - dnf_patch_size_line != ''
        - dnf_required_space_mb > var_available_space_mb

    - name: Final success message
      debug:
        msg: "Prepatch check passed. System is ready for patching."
      when:
        - dnf_patch_size_line == '' or dnf_required_space_mb <= var_available_space_mb
