---
- name: Check for read-only files on a Linux server
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Find all regular files (excluding system dirs for safety)
      ansible.builtin.find:
        paths: /
        recurse: yes
        file_type: file
        excludes:
          - /proc
          - /sys
          - /dev
          - /run
          - /tmp
          - /var/tmp
      register: all_files

    - name: Filter files that are read-only (no write permission)
      set_fact:
        readonly_files: >-
          {{
            all_files.files
            | selectattr('mode', 'match', '^0?4[0-7][0-7][0-7]$')
            | selectattr('mode', 'search', '^[0-7]*4[0-4][0-4]$')
            | list
          }}

    - name: Print total number of read-only files
      debug:
        msg: "Found {{ readonly_files | length }} read-only files"

    - name: Display read-only file paths
      debug:
        var: item.path
      loop: "{{ readonly_files }}"
      when: readonly_files | length > 0
